name: Dev PR CI

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  id-token: write

jobs:
  dev-pr-ci:
    uses: baerae-zkap/zkap-workflows/.github/workflows/dev-pr-ci.yml@main
    with:
      package-manager: npm
      use-private-packages: false
      runner: self-hosted
    secrets: inherit
