name: Dev PR CI

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read
  id-token: write

jobs:
  dev-pr-ci:
    uses: baerae-zkap/zkap-workflows/.github/workflows/dev-pr-ci.yml@feat/pr-ci-enhancements
    with:
      package-manager: npm
      use-private-packages: false
    secrets: inherit
